# Copyright Radu-Andrei Dumitrescu 322CA 2021

all:
	g++ server.cpp -g -Wall -o server -std=c++11;
	g++ client.cpp -g -Wall -o client -std=c++11;


server:
	g++ server.cpp -g -Wall -o server -std=c++11;

client:
	g++ client.cpp -g -Wall -o client -std=c++11;

clean:
	rm -rf client server
